[ITSASU-1148] Ensure error messages have a terminating full stop so that screen readers can handle them.

diff --git a/scripts/start b/scripts/start
--- a/scripts/start
+++ b/scripts/start
@@ -8,25 +8,25 @@ function die() {
 }
 
 MONGO_PORT=27017
-which nc &>/dev/null && nc -vz localhost $MONGO_PORT 2>/dev/null || die "Can't find MongoDB on port $MONGO_PORT (using: nc -vz localhost $MONGO_PORT)"
+which nc &>/dev/null && nc -vz localhost $MONGO_PORT 2>/dev/null || die "Can't find MongoDB on port $MONGO_PORT (using: nc -vz localhost $MONGO_PORT) - you may want to run 'docker run -p 27017:27017 -d mongo'"
 
 which sm &>/dev/null || die "Can't find Service Manager"
 
-if [[ -z $1 && "$1" == "--minimal" ]]; then
-   sm --start ITSA_SUBSC_DEP
-   sm --start AGENTS_TAX_ENROLMENTS
-   sm --start INCOME_TAX_SUBSCRIPTION
-   sm --start INCOME_TAX_SUBSCRIPTION_SELF_EMPLOYED_FRONTEND
-   sm --start INCOME_TAX_SUBSCRIPTION_STUBS
-   sm --start INCOME_TAX_SUBSCRIPTION_ELIGIBILITY
-   sm --start INCOME_TAX_SUBSCRIPTION_FRONTEND
-   sm --start TAX_ENROLMENTS
+if [[ "$1" == "--minimal" ]]; then
+   sm --start ITSA_SUBSC_DEP "${@:2}"
+   sm --start AGENTS_TAX_ENROLMENTS "${@:2}"
+   sm --start INCOME_TAX_SUBSCRIPTION "${@:2}"
+   sm --start INCOME_TAX_SUBSCRIPTION_SELF_EMPLOYED_FRONTEND "${@:2}"
+   sm --start INCOME_TAX_SUBSCRIPTION_STUBS "${@:2}"
+   sm --start INCOME_TAX_SUBSCRIPTION_ELIGIBILITY "${@:2}"
+   sm --start INCOME_TAX_SUBSCRIPTION_FRONTEND "${@:2}"
+   sm --start TAX_ENROLMENTS "${@:2}"
 else
-   sm --start ITSA_SUBSC_ALL
+   sm --start ITSA_SUBSC_ALL "$@"
 fi
-
+sleep 5
 sm --stop INCOME_TAX_SUBSCRIPTION_ELIGIBILITY_FRONTEND
-
+sleep 5
 sbt "run 9589 -Dapplication.router=testOnlyDoNotUseInAppConf.Routes"
    
 
